#!/bin/bash

docker-compose down

docker system prune -af

cat <<EOF > .env
DB_HOST_ORDER=${DB_HOST_ORDER}
DB_PORT_ORDER=${DB_PORT_ORDER}
DB_USER_ORDER=${DB_USER_ORDER}
DB_PASSWORD_ORDER=${DB_PASSWORD_ORDER}
DB_NAME_ORDER=${DB_NAME_ORDER}
STOCK_QUERY_SERVICE_URL=${STOCK_QUERY_SERVICE_URL}
STOCK_RESERVATION_SERVICE_URL=${STOCK_RESERVATION_SERVICE_URL}
STOCK_UPDATE_URL=${STOCK_UPDATE_URL}
EOF

docker-compose pull

docker-compose up -d

