openapi: 3.0.0
info:
  title: Create Product API
  description: API for managing products in an e-commerce system.
  version: 1.0.0
servers:
  - url: http://18.234.5.75:3001/api/products
    description: Deploy EC2
paths:
  /create-product:
    post:
      summary: Create a new product
      description: Adds a new product to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "12345"
                name:
                  type: string
                  example: "Notebook"
                detail:
                  type: string
                  example: "A high-quality notebook for students."
                price:
                  type: number
                  format: float
                  example: 12.99
                category:
                  type: string
                  example: "Stationery"
                brand:
                  type: string
                  example: "PaperMate"
                stock:
                  type: integer
                  example: 100
                image_url:
                  type: string
                  example: "https://image/notebook.jpg"
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product created successfully"
                  product:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "12345"
                      name:
                        type: string
                        example: "Notebook"
                      detail:
                        type: string
                        example: "A high-quality notebook for students."
                      price:
                        type: number
                        format: float
                        example: 12.99
                      category:
                        type: string
                        example: "Stationery"
                      brand:
                        type: string
                        example: "PaperMate"
                      stock:
                        type: integer
                        example: 100
                      image_url:
                        type: string
                        example: "https://image/notebook.jpg"
        "400":
          description: Bad request, missing required fields
        "500":
          description: Internal server error
