#!/bin/bash

docker-compose down

docker system prune -af

cat <<EOF > .env
DB_HOST_CART=${DB_HOST_CART}
DB_PORT_CART=${DB_PORT_CART}
DB_USER_CART=${DB_USER_CART}
DB_PASSWORD_CART=${DB_PASSWORD_CART}
DB_AUTH_SOURCE_CART=${DB_AUTH_SOURCE_CART}
PRODUCT_DETAIL_SERVICE=${PRODUCT_DETAIL_SERVICE}
INVENTORY_SERVICE=${INVENTORY_SERVICE}
CART_SERVICE_URL=${CART_SERVICE_URL}
ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
JWT_SECRET=${JWT_SECRET_KEY}
EOF

docker-compose pull

docker-compose up -d

