#!/bin/bash

docker-compose down

docker system prune -af

cat <<EOF > .env
DB_CONNECTION_CATALOG=${DB_CONNECTION_CATALOG}
DB_HOST_CATALOG=${DB_HOST_CATALOG}
DB_PORT_CATALOG=${DB_PORT_CATALOG}
DB_DATABASE_CATALOG=${DB_DATABASE_CATALOG}
DB_USERNAME_CATALOG=${DB_USERNAME_CATALOG}
DB_PASSWORD_CATALOG=${DB_PASSWORD_CATALOG}
APP_DEBUG_CATALOG=${APP_DEBUG_CATALOG}
LIST_PRODUCT_SERVICE_GRAPHQL=${LIST_PRODUCT_SERVICE_GRAPHQL}
EOF

docker-compose pull

docker-compose up -d

