name: Deploy User Management

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      
      - name: 🔍 Verificar Variables en GitHub Actions
        run: |
          echo " REGISTRATION_DB_URL is set" && test -n "${{ secrets.REGISTRATION_DB_URL }}" && echo " OK" || echo " MISSING"
          echo " LOGIN_DB_URL is set" && test -n "${{ secrets.LOGIN_DB_URL }}" && echo " OK" || echo " MISSING"
          echo " LOGOUT_DB_URL is set" && test -n "${{ secrets.LOGOUT_DB_URL }}" && echo " OK" || echo " MISSING"
          echo " JWT_SECRET_KEY is set" && test -n "${{ secrets.JWT_SECRET_KEY }}" && echo " OK" || echo " MISSING"
          echo " JWT_ALGORITHM is set" && test -n "${{ secrets.JWT_ALGORITHM }}" && echo " OK" || echo " MISSING"
          echo " JWT_EXPIRATION_MINUTES is set" && test -n "${{ secrets.JWT_EXPIRATION_MINUTES }}" && echo " OK" || echo " MISSING"

      - name: Configurar SSH y desplegar en EC2
        env:
          REGISTRATION_DB_URL: ${{ secrets.REGISTRATION_DB_URL }}
          LOGIN_DB_URL: ${{ secrets.LOGIN_DB_URL }}
          LOGOUT_DB_URL: ${{ secrets.LOGOUT_DB_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
          JWT_EXPIRATION_MINUTES: ${{ secrets.JWT_EXPIRATION_MINUTES }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_USER: "ec2-user"
          EC2_HOST: "3.220.99.156"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            echo " Expor varible to EC2..."
            echo "export REGISTRATION_DB_URL='$REGISTRATION_DB_URL'" >> ~/.bashrc
            echo "export LOGIN_DB_URL='$LOGIN_DB_URL'" >> ~/.bashrc
            echo "export LOGOUT_DB_URL='$LOGOUT_DB_URL'" >> ~/.bashrc
            echo "export JWT_SECRET_KEY='$JWT_SECRET_KEY'" >> ~/.bashrc
            echo "export JWT_ALGORITHM='$JWT_ALGORITHM'" >> ~/.bashrc
            echo "export JWT_EXPIRATION_MINUTES='$JWT_EXPIRATION_MINUTES'" >> ~/.bashrc
            source ~/.bashrc
            env | grep DB_URL
            env | grep JWT
            cd /home/ec2-user/Paper-chain-project/user-management
            bash deploy.sh
          EOF

